export type DisplayMode =
  | 'slides'
  | 'newContent'
  | 'slideNarrative'
  | 'customBuilder'
  | 'Points'
  | 'Timeline'
  | 'Images'
  | 'Table'
  | 'People'
  | 'Graphs'
  | 'Statistics'
  | 'SlideNarrative'
